# 開発環境用Dockerfile

FROM ruby:3.0.4
WORKDIR /app

# Node.js v14 https://github.com/nodesource/distributions#debinstall
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt update && apt install -y git less nodejs tig vim

# yarn
RUN npm install -g yarn

ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV EXECJS_RUNTIME=Node


# https://sinsoku.hatenablog.com/entry/2021/03/24/100000
